# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1
# Using template deno.tera

EAPI=8

CRATES="
"
#NOTE: update deno.tera for long term changes

DENO_STD_HASH="9c5b7101545e53f031b6e7757da655d5d8ee3fc2"
NODE_TEST_HASH="c5baef08e6692c16940b82e2ee5d778a11da64d7"
CHROMIUM_CRATES_HASH="ba6ceef355cf48cc50493296d4fc862d9745b742"
V8_VER="147.4.0"

LLVM_COMPAT=( 21 ) #todo 21 only?
#LLVM_OPTIONAL=1

PYTHON_COMPAT=( python3_{11..14} )

RUST_MIN_VER="1.91.0"
RUST_MAX_VER="1.94.1"

inherit cargo check-reqs llvm-r2 multiprocessing python-any-r1 shell-completion toolchain-funcs

DESCRIPTION="A modern runtime for JavaScript and TypeScript"
HOMEPAGE="https://deno.land/"

V8_BASE_URL="https://github.com/denoland/rusty_v8/releases/download/v${V8_VER}"
V8_TARGET="x86_64-unknown-linux-gnu"
V8_TYPE="simdutf_release"
SRC_URI="${CARGO_CRATE_URIS}"
SRC_URI+="
	https://github.com/denoland/deno/archive/refs/tags/v${PV}.tar.gz -> deno-${PV}.tar.gz
	https://github.com/jgenco/jgenco-overlay-files/releases/download/deno-${PV}/deno-${PV}-crates.tar.xz
	test? (
		https://github.com/denoland/std/archive/${DENO_STD_HASH}.tar.gz -> deno_std-${DENO_STD_HASH::8}.tar.gz
		https://github.com/denoland/node_test/archive/${NODE_TEST_HASH}.tar.gz -> deno_node_test-${NODE_TEST_HASH:0:8}.tar.gz
	)
	v8-prebuilt? (
		${V8_BASE_URL}/librusty_v8_${V8_TYPE}_${V8_TARGET}.a.gz -> librusty_v8_${V8_VER}_${V8_TYPE}_${V8_TARGET}.a.gz
		${V8_BASE_URL}/src_binding_${V8_TYPE}_${V8_TARGET}.rs   -> librusty_v8_${V8_VER}_${V8_TYPE}_${V8_TARGET}.binding.rs
	)
	!v8-prebuilt? (
		https://github.com/jgenco/jgenco-overlay-files/releases/download/deno-chrome-${PV}/v8_third_party_rust_${CHROMIUM_CRATES_HASH:0:8}.tar.xz
	)
"
LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD Boost-1.0
	CC0-1.0 ISC MIT MIT-0 MPL-2.0 MPL-2.0 openssl Unicode-3.0
	Unicode-DFS-2016 ZLIB
"
#rg license\ = third_party/rust/chromium_crates_io/vendor/*/Cargo.toml -IN|sed "s/license = //"|sort -u
SLOT="0"
KEYWORDS="~amd64"
IUSE="llvm v8-prebuilt test"
RESTRICT="mirror !test? ( test )"

#REQUIRED_USE="!v8-prebuilt? ( ${LLVM_REQUIRED_USE} )"
#REQUIRED_USE="v8-prebuilt? ( !sys-libraries )"

DEPEND="${PYTHON_DEPS}"
BDEPEND="
	>=dev-build/gn-0.2318
	dev-build/ninja
	virtual/zlib

	$(llvm_gen_dep '
		llvm-core/clang:${LLVM_SLOT}
	')
	llvm? ( $(llvm_gen_dep '
		llvm-core/llvm:${LLVM_SLOT}
	') )
	!v8-prebuilt? (
		dev-util/bindgen
		|| (
			$(llvm_gen_dep 'llvm-core/lld:${LLVM_SLOT}')
			>=sys-devel/mold-2.41.0
		)
	)
	test? (
		dev-util/esbuild
		net-misc/curl
	)
"
RDEPEND="!dev-lang/deno-bin"
PATCHES=(
	"${FILESDIR}/deno-2.4.5-local_esbuild.patch"
	"${FILESDIR}/deno-2.7.14-disable_tests.patch"
)
DOCS=(Releases.md LICENSE.md README.md)

function find_crate() {
	[[ ${#} -eq 0 ]] && die "No crate name provided"
	cd ${ECARGO_VENDOR}
	for crate in *;do
		if [[ ${crate} =~ ${1} ]];then
			[[ ${2} == "p" ]] && echo -n "${ECARGO_VENDOR}/"
			echo "${crate}" && return
		fi
	done
	die "Crate $1 not found"
}

disk_space_check() {
	local disk_space="13"
	local disk_space_test="7"
	if ! use v8-prebuilt; then
		disk_space="$(usex llvm 15 19)"
		disk_space_test="$(usex llvm 7 2)"
	fi
	use test && disk_space=$((${disk_space} + ${disk_space_test}))
	local CHECKREQS_DISK_BUILD="${disk_space}G"
	check-reqs_${EBUILD_PHASE_FUNC}
}
pkg_pretend() {
	disk_space_check
}

pkg_setup() {
	disk_space_check
	#use llvm && llvm-r2_pkg_setup
	rust_pkg_setup
	python_setup
}

src_unpack() {
	cargo_src_unpack
	if ! use v8-prebuilt; then
		mv "${WORKDIR}/chromium_crates_io" "$(find_crate ^v8- p)/third_party/rust" || die
	fi
	if use test; then
		rmdir "${S}/tests/"{util/std,node_compat/runner/suite} || die "Failed to remove test dirs"
		mv "${WORKDIR}/std-${DENO_STD_HASH}/" \
			"${S}/tests/util/std" || die "Failed to move deno-std into position"
		mv "${WORKDIR}/node_test-${NODE_TEST_HASH}/" \
		"${S}/tests/node_compat/runner/suite" || die
	fi
}

src_prepare() {
	eapply -d "$(find_crate ^v8- p)" -- \
		"${FILESDIR}/v8-142.2.0-toolchainless.patch" \
		"${FILESDIR}/v8-0.42.0-disable-auto-ccache.patch" \
		"${FILESDIR}/v8-135.1.0-v8-out_dir.patch" \
		"${FILESDIR}/v8-0.105.0-v8-ninja-verbose.patch" \
		\
		"${FILESDIR}/v8-145.0.0-rustc_nightly_capability.patch" \
		"${FILESDIR}/v8-145.0.0-gcc15.patch"
	# only for <clang23
	eapply -d "$(find_crate ^v8- p)" -- \
		"${FILESDIR}/v8-147.4.0-bigint.patch" \
		"${FILESDIR}/clang_22.patch"

	#see v8-out_dir.patch
	export V8_OUT_DIR="${WORKDIR}/v8_out_dir"
	mkdir -p "${V8_OUT_DIR}"/gn_out \
		"$(cargo_target_dir)" \
		"${S}/target/"$(usex debug debug release) || die
	ln -s "${V8_OUT_DIR}"/gn_out "$(cargo_target_dir)" || die
	#cross-compile has a different path
	if [[ ! -h "${S}/target/"$(usex debug debug release)/gn_out ]]; then
		ln -s "${V8_OUT_DIR}"/gn_out "${S}/target/"$(usex debug debug release) || die
	fi

	#This comes from www-client/chromium - liable to change
	sed -i -e '/is_clang && !(is_a_target_toolchain && is_cronet_build)) {/,+2d' \
		"$(find_crate ^v8- p)/build/config/compiler/BUILD.gn" || die

	#https://github.com/denoland/rusty_v8/issues/1145 - only for testing?
	ln -s "$(find_crate deno_core_icudata p)/src" \
		"$(find_crate ^v8- p)/third_party/icu/common" || die

	###fix tests###
	if use test; then
		# gcc has alot more debuging data and increases the space need for test BY ALOT
		# I dont't think this will change the results
		! use llvm && ( sed -i 's/"-g1"/"-g0"/' \
			"$(find_crate ^v8- p)/build/config/compiler/BUILD.gn" || die )
		#https://github.com/denoland/deno_third_party/tree/master/prebuilt/linux64
		mkdir -p third_party/prebuilt/linux64
		local esbuild_bin=("${EPRFIX}/usr/bin/esbuild"*)
		echo "Using esbuild:${esbuild_bin[-1]}" #pick the latest esbuild
		ln -s "${esbuild_bin[-1]}" third_party/prebuilt/linux64/esbuild-x64 || die
	fi
	#disables test that need network
	awk -i inplace \
		'BEGIN {p = 0}
		/(dns|test-http-https-default-ports).*{/ {p=1}
		{ if(p) print "//"$0"// need internet";else print $0 }
		/},/ {p=0}' \
		tests/node_compat/config.jsonc || die
	#sockets work in terminal; sytle does not, quiet error for now
	sed -Ei  "/test-fs-cp-(sync-copy|async)-socket/d;/test-util-styletext.js/d" \
		tests/node_compat/config.jsonc || die
	#panics but not when run on terminal :|
	rm tests/napi/worker_termination_* || die

	local spec_dir="tests/specs"
	local spec_tests=(
		${spec_dir}/cert/deno_land_unsafe_ssl #net
		${spec_dir}/cert/ip_address_unsafe_ssl #net
		${spec_dir}/compile/permissions_denied #LD_PRELOAD? -try again
		${spec_dir}/future/unstable_flags #try again might import @std
		${spec_dir}/import_map/import_map_config #net
		${spec_dir}/info/import_map #net - try again
		${spec_dir}/npm/lifecycle_scripts # TODO requires node headers for node-gyp
		${spec_dir}/npm/lock_file_integrity_failure # net needs vue
		${spec_dir}/npm/playwright_compat #d/ls playwright
		${spec_dir}/permission/deny_run_binary_absolute_path #LD_PRELOAD? -try again
		${spec_dir}/run/_017_import* #net
		${spec_dir}/run/allow_run_allowlist #LD_PRELOAD? -try allow_run?
		${spec_dir}/upgrade #upgrade/net
		${spec_dir}/run/sslkeylogfile #net
		tests/unit_node/dns_test.ts # net
	)
	rm -r ${spec_tests[@]} || die
	find ${spec_dir} -type d -empty -print -delete || die

	sed "s#/usr/bin/sh#${EPREFIX}/bin/sh#" -i tests/unit/serve_test.ts || die
	#this allows the test_server to serve EXACT tarballs
	sed -Ei 's/(flate2.*)features = \["default"\](.*)/\1features = ["zlib-ng-compat"]\2/' \
		tests/util/server/Cargo.toml || die
	use test && ( sed -i "s/0.25.5/$(esbuild-0.25 --version)/" tests/util/server/npm.rs || die )
	###end fix Test###

	default
}

src_configure() {
	cd cli || die "Failed to change dir cli"
	local myfeatures=(
		#__vendored_zlib_ng
	)
	cargo_src_configure --no-default-features
}

src_compile() {
	#inspired by www-client/chromium and alpine's port
	local gn_conf=(
		treat_warnings_as_errors=false
		#custom_toolchain=\"//build/toolchain/linux/unbundle:default\"
		chrome_pgo_phase=0 #offer pgo option?
		fatal_linker_warnings=false
		is_debug=false
		#symbol_level=0
		#use_curtom_libcxx=false
		use_sysroot=false
		toolchain_for_rust_host_build_tools=false
		#rustc_nightly_capability=true
		#use_chromium_rust_toolchain=true

		"use_lld=true"
		"clang_use_chrome_plugins=false"
		"use_clang_modules=false" # M141 enables this for the linux platform by default.
		"clang_base_path=\"$(get_llvm_prefix)/\""
		"rust_bindgen_root=\"${EPREFIX}/usr/\""
		"rust_sysroot_absolute=\"$(get_rust_prefix)\""
		"rustc_version=\"${RUST_SLOT}\""
	)

	if use llvm; then
		einfo "Clang version: $(clang-fullversion) - $(get_llvm_prefix)"
		gn_conf+=(is_clang=true)
		tc-ld-is-mold && gn_conf+=("experimental_linker_path=\"${EPREFIX}/usr/bin/ld.mold\"")
	else
		export DISABLE_CLANG=true
		einfo "GCC version: $(gcc-fullversion)"
		gn_conf+=(use_custom_libcxx=false)
		# gcc doesn't support --ld-path
		tc-ld-is-mold && ( sed -i 's/"-fuse-ld=lld"/"-fuse-ld=mold"/' \
			"$(find_crate ^v8- p)/build/config/compiler/BUILD.gn" || die )

	fi

	#They didn't include the pgo files tools/builtins-pgo/{x64,arm64}.profile
	#https://github.com/denoland/rusty_v8/pull/1063
	#https://github.com/Homebrew/homebrew-core/pull/108838
	gn_conf+=(v8_builtins_profiling_log_file=\"\")

	export LLVM_CONFIG_PATH=$(get_llvm_prefix)/bin/llvm-config
	export CLANG_PATH="$(get_llvm_prefix)/bin"
	export LIBCLANG_PATH="$(get_llvm_prefix)/$(get_libdir)"

	export RUSTC_BOOTSTRAP=$(usex v8-prebuilt 0 1) #with 0 check if w/o rustc_nightly_capability.patch works
	export V8_FROM_SOURCE=$(usex v8-prebuilt false true)

	local prebuilt_prefix="${DISTDIR}/librusty_v8_${V8_VER}_${V8_TYPE}_${V8_TARGET}"
	export RUSTY_V8_ARCHIVE=$(usex v8-prebuilt "${prebuilt_prefix}.a.gz" "")
	export RUSTY_V8_SRC_BINDING_PATH=$(usex v8-prebuilt "${prebuilt_prefix}.binding.rs" "")

	#export SCCACHE=
	#export CCACHE=
	export GN="${EPREFIX}/usr/bin/gn"
	export NINJA="${EPREFIX}/usr/bin/ninja"
	export CLANG_BASE_PATH=$(get_llvm_prefix)
	export NUM_JOBS=$(makeopts_jobs)

	export PRINT_GN_ARGS=false
	export GN_ARGS="${gn_conf[@]}"
	einfo "GN_ARGS=${GN_ARGS}"
	einfo "EXTRA_GN_ARGS=${EXTRA_GN_ARGS}"

	pushd cli > /dev/null || die "Failed to change dir cli"
	cargo_src_compile -vv
	popd > /dev/null

	if use test;then
		einfo "Building test server..."
		local tests_bin=(
			"tests/util/server:--release"
			"tests/specs/node/child_process_extra_pipes/test-pipe/src:"
			"tests/ffi:--release"
		)
		for entry in ${tests_bin[@]};do
			local path="${entry%:*}"
			local options="${entry#*:}"
			pushd ${path}> /dev/null || die
			cargo_env ${CARGO} build ${options} || die "failed to build test server"
			popd
		done

		pushd tests/specs/node/child_process_extra_pipes/test-pipe/target || die
		if [[ ! -f debug/test-pipe ]] ;then
			mkdir debug || die
			ln -s ../$(rust_abi)/debug/test-pipe  debug/test-pipe || die
		fi
		popd > /dev/null
	fi

	"$(cargo_target_dir)"/deno completions bash > deno.sh   || die "Failed to create bash completion file"
	"$(cargo_target_dir)"/deno completions fish > deno.fish || die "Failed to create fish completion file"
	"$(cargo_target_dir)"/deno completions zsh  > _deno     || die "Failed to create zsh completion file"
}
src_test() {
	cargo_src_test --no-fail-fast
}

src_install() {
	cargo_src_install --path cli
	einstalldocs

	newbashcomp deno.sh deno
	dofishcomp deno.fish
	dozshcomp _deno
}

pkg_postinst() {
	if ! tc-is-clang ; then
		#--When cargo_src_compile -vv
		#QA Check notes gcc warns about return-local-addr for the following file
		#${ECARGO_VENDOR}/${v8_dir}/third_party/icu/source/i18n/formattedvalue.cpp:212
		#https://github.com/unicode-org/icu/blob/main/icu4c/source/i18n/formattedvalue.cpp#L212
		#the source code mentions this is a false positive
		#come up with some text to inform the user
		#TODO unbundle third party libs(ICU,zlib) if possible
		:
	fi
}
