# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
"

declare -A GIT_CRATES=(
	[typst-dev-assets]='https://github.com/typst/typst-dev-assets;53c12796fc6c62e12af8788ab80ebed686d5eedb;typst-dev-assets-%commit%'
)

RUST_MIN_VER="1.92"

inherit cargo shell-completion

DESCRIPTION="A new markup-based typesetting system that is powerful and easy to learn"
HOMEPAGE="
	https://typst.app/
	https://github.com/typst/typst
"
SRC_URI="
	https://github.com/typst/typst/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/jgenco/jgenco-overlay-files/releases/download/${P}/typst-${PV}-crates.tar.xz
	${CARGO_CRATE_URIS}
"
LICENSE="Apache-2.0"
LICENSE+=" embed-fonts? ( OFL-1.1 GFL BitstreamVera )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD-2 BSD CC0-1.0 ISC MIT MPL-2.0 UoI-NCSA Unicode-3.0
	Unicode-DFS-2016 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="
	dev-libs/openssl
"
DEPEND="${RDEPEND}"
BDEPEND="
	dev-vcs/git
"

IUSE="doc embed-fonts http-server test"
RESTRICT="mirror !test? ( test )"

DOCS=(LICENSE NOTICE README.md)

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"
src_prepare() {
	sed -i "s/^strip = true$/strip = false/" Cargo.toml || die
	default
}

src_configure() {
	local myfeatures=(
		$(usev embed-fonts embedded-fonts)
		$(usev http-server)
	)
	cargo_src_configure --no-default-features
}

src_compile() {
	export GEN_ARTIFACTS="${S}/artifacts"
	local typst_hash="$(gunzip -c "${DISTDIR}/typst-${PV}.tar.gz" |git get-tar-commit-id)"
	assert "Failed to get commit hash"
	export TYPST_COMMIT_SHA="${typst_hash:0:8}"
	cargo_src_compile -p typst-cli
	if use doc;then
		cargo_env ${CARGO} docit compile || die
	fi
}

src_test() {
	cargo_src_test --all
}

src_install() {
	cargo_src_install --path crates/typst-cli

	pushd "${GEN_ARTIFACTS}" > /dev/null || die
	newbashcomp typst.bash typst
	dofishcomp typst.fish
	dozshcomp _typst
	doman *.1
	popd

	einstalldocs
	use doc && dodoc -r docs/dist/site
}
