# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES=""

BIOME_URL="https://github.com/biomejs/biome"
BIOME_COMMIT="c13fc60726883781e4530a4437724273b560c8e0"
declare -A GIT_CRATES=(
	[biome_console]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_console"
	[biome_deserialize]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_deserialize"
	[biome_deserialize_macros]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_deserialize_macros"
	[biome_diagnostics]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_diagnostics"
	[biome_diagnostics_categories]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_diagnostics_categories"
	[biome_diagnostics_macros]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_diagnostics_macros"
	[biome_formatter]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_formatter"
	[biome_json_factory]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_json_factory"
	[biome_json_parser]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_json_parser"
	[biome_json_syntax]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_json_syntax"
	[biome_line_index]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_line_index"
	[biome_markup]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_markup"
	[biome_parser]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_parser"
	[biome_rowan]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_rowan"
	[biome_string_case]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_string_case"
	[biome_text_edit]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_text_edit"
	[biome_text_size]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_text_size"
	[biome_unicode_table]="${BIOME_URL};${BIOME_COMMIT};biome-%commit%/crates/biome_unicode_table"
	[tower-lsp-macros]='https://github.com/lionel-/tower-lsp;49ef549eaa9f74b71e212cf513283af4ad748a81;tower-lsp-%commit%/tower-lsp-macros'
	[tower-lsp]='https://github.com/lionel-/tower-lsp;49ef549eaa9f74b71e212cf513283af4ad748a81;tower-lsp-%commit%'
	[tree-sitter-r]='https://github.com/r-lib/tree-sitter-r;daa26a2ff0d9546e9125c7d8bcec046027f02070;tree-sitter-r-%commit%'
)

RUST_MIN_VER="1.87.0"
RUST_MAX_VER="1.89.0"

inherit cargo edo

DESCRIPTION="R formatter and language server"
HOMEPAGE="https://github.com/posit-dev/air"
SRC_URI="
	https://github.com/posit-dev/air/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/jgenco/jgenco-overlay-files/releases/download/${P}/${P}-crates.tar.xz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="air-${PV}-crates.tar.xz"
fi

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT MPL-2.0 Unicode-3.0
	Unicode-DFS-2016
"
SLOT="0"
KEYWORDS="~amd64"
IUSE="doc test"
RESTRICT="mirror !test? ( test )"

DEPEND="
	doc? (
		|| (
			app-text/quarto-cli
			app-text/quarto-cli-bin
		)
	)
	test? ( dev-util/cargo-nextest )
"

src_prepare() {
	default
	#I don't know why this is needed but this is inspired by app-editors/zed
	local biome_git=" = { git = \"${BIOME_URL}\", rev = \"${BIOME_COMMIT}"
	local biome_path=" = \\{ path = \"${WORKDIR}/biome-${BIOME_COMMIT}"
	for crate in ${!GIT_CRATES[@]}; do
		[[ ! "${crate}" =~ biome_ ]] && continue
		sed -e "s#${crate}${biome_git}#${crate}${biome_path}/crates/${crate}#" \
			-i "${S}/Cargo.toml" || die "Cargo fetch workaround failed"
	done
}

src_compile() {
	cd crates/air
	cargo_src_compile
	if use doc; then
		cd ../../docs
		quarto render --output-dir guide || die
	fi
}
src_install() {
	cargo_src_install --path crates/air

	einstalldocs

	if use doc; then
		dodoc -r docs/guide
	fi
}

src_test() {
	local -x COLUMNS=100
	edo ${CARGO} nextest run $(usev !debug '--release') --no-fail-fast
}
